source 'https://rubygems.org'

gem 'rails', '3.2.13'
gem 'foreman'
gem 'unicorn'
gem 'thin'
gem 'pg'
gem 'devise'
gem 'jquery-rails'
gem 'execjs'
gem 'em-websocket'
gem 'em-hiredis'
gem 'redis'
gem 'json'
gem 'zendesk_api'
gem 'pry-rails'

group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'
  gem 'uglifier', '>= 1.0.3'
end

group :development do
  gem 'capistrano'
  gem 'quiet_assets'
end

group :development, :test do
  gem 'rspec-rails'
  gem 'factory_girl_rails'
end

group :test do
  gem 'nyan-cat-formatter'
  gem 'capybara'
end
